version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    container_name: web_container 
    volumes:
      - ./server/www:/var/www/html
    ports:
      - 8080:80
  mysql:
    container_name: db_container
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=root
    ports:
    - 6033:3306
    volumes:
      - ~/docker/mysql-data:/var/lib/mysql